name: Zw2Afk
version: 2.0.3
description: Damit kann man afk gehen oder wiederkommen
api-version: "1.20"
author: Zweistein2

softdepend: [DiscordSRV, PermissionsEx]

main: de.zweistein2.plugins.zw2afk.Zw2Afk

commands:
  afk:
    description: Setzt dich afk
    usage: Nutze /<command> [Nachricht] um den Befehl richtig zu verwenden
  re:
    description: Setzt dich wieder in den Normalzustand
    usage: Nutze /<command> um den Befehl richtig zu verwenden